framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            async:
                dsn: '%env(RABBITMQ_URL)%'
                options:
                    exchange:
                        name: 'messages'
                        type: 'direct'
                    queues:
                        messages:
                            binding_keys: ['messages']

            failed: 'doctrine://default?queue_name=failed'  # Stores failed messages in the DB
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\AuditLogMessage': async


when@test:
   framework:
       messenger:
           transports:
               # replace with your transport name here (e.g., my_transport: 'in-memory://')
               # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
               async: 'in-memory://'
